# -*- coding: utf-8 -*-
"""Day1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OR5_rSNVa4OA0Ds7svMcHW6K0-8jChFk
"""

import pandas as pd

from google.colab import files
import os

# Check if the file already exists to avoid re-uploading
if not os.path.exists('student_performance.csv'):
    print("Uploading 'student_performance.csv'...")
    uploaded = files.upload()
    for fn in uploaded.keys():
        print(f'User uploaded file "{fn}"')
else:
    print("'student_performance.csv' already exists.")

df=pd.read_csv('student_performance.csv')

df.head()

print("shape of dataset:",df.shape)
print("shape of column:",df.shape[1])

print(df.columns.tolist())

print(df.index.tolist())

print(df.dtypes)

display(df.describe())

print("Number of missing values in each column:")
print(df.isnull().sum())

import numpy as np
df.loc[df.index[:5],'math_score'] = np.nan
df.isna().sum()

department_counts = df['department'].value_counts()
print("Number of members in each department:")
display(department_counts)

gender_counts = df['gender'].value_counts()
print("Number of male and female members:")
display(gender_counts)

cs_students_df = df[df['department'] == 'Computer Science']

print("Students in Computer Science Department:")
display(cs_students_df.head())

chennai_mumbai_students = df[df['city'].isin(['Chennai', 'Mumbai'])]
display(chennai_mumbai_students[['name', 'city', 'programming_score']])

attendance_students = df[df['attendance_percentage'] <= 70]
print("Students with attendance percentage <= 70:")
display(attendance_students[['name', 'department', 'attendance_percentage']])

df['total_score'] = df[['math_score', 'science_score', 'english_score', 'programming_score']].fillna(0).sum(axis=1)

print("DataFrame with total_score:")
display(df[['name', 'math_score', 'science_score', 'english_score', 'programming_score', 'total_score']].head())

import pandas as pd

df = pd.read_csv('/content/student_performance.csv')

print(df.head())

import os
print(os.listdir('/content'))

print("=" * 50)
print("      STUDENT PERFORMANCE EXPLORER")
print("=" * 50)

print("\nDATASET OVERVIEW")
print("-" * 30)

print(f"Total Students : {len(df)}")
print(f"Total Columns : {len(df.columns)}")
print(f"Unique Departments : {df['department'].nunique()}")

print("\nDEPARTMENT WISE ANALYSIS")
print("-" * 30)

print(df['department'].value_counts())

print("\nSCORE ANALYSIS")
print("-" * 30)

print(f"Highest Math Score : {df['math_score'].max()}")
print(f"Lowest Math Score : {df['math_score'].min()}")
print(f"Average Math Score : {df['math_score'].mean():.2f}")
print(f"Average Programming Score : {df['programming_score'].mean():.2f}")
print(f"Average Attendance : {df['attendance_percentage'].mean():.2f}")

df['total_score'] = df['math_score'] + df['programming_score']

print(df.groupby('gender')['total_score'].mean())

print("\nTOP 5 PERFORMERS")
print("-" * 30)

top_students = df.sort_values(by='total_score', ascending=False).head(5)

for index, row in top_students.iterrows():
    print(f"Name : {row['name']}")
    print(f"Department : {row['department']}")
    print(f"Total Score : {row['total_score']}")
    print("-" * 20)

print("\nATTENDANCE ANALYSIS")
print("-" * 30)

low_attendance = df[df['attendance_percentage'] < 75]

if len(low_attendance) > 0:
    print(low_attendance[['name', 'department', 'attendance_percentage']])
else:
    print("All students have attendance above 75%")

#How many students are from the Electronics Department?
electronics_students = len(df[df['department'] == 'Electronics'])

print("Students from Electronics Department :", electronics_students)

#What is the average attendance of female students?
female_attendance = df[df['gender'] == 'Female']['attendance_percentage'].mean()

print("Average Attendance of Female Students :", female_attendance)

#Who is the student with the lowest programming score?
lowest_prog_student = df.loc[df['programming_score'].idxmin(), 'name']

print("Student with Lowest Programming Score :", lowest_prog_student)

#How many students scored above 80 in math?
above_80_math = len(df[df['math_score'] > 80])

print("Students Scored Above 80 in Math :", above_80_math)

#What is the average total_score for students with attendance above 90%?
avg_total = df[df['attendance_percentage'] > 90]['total_score'].mean()

print("Average Total Score :", avg_total)