# -*- coding: utf-8 -*-
"""Day2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169F2MIBUHqjEwRPeBFvQI212BbExCp3R
"""

import sqlite3

import pandas as pd

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')
print("All libraries imported sucessfully")
print("pandas version")

df = pd.read_csv('/content/student_performance.csv')
print(f"Number of rows: {df.shape[0]}, Number of columns: {df.shape[1]}")

"""Let's inspect the first few rows of the dataset to understand its structure and content."""

df.head(3)

conn=sqlite3.connect('college.db')
cursor=conn.cursor()
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)
cursor.execute('SELECT count(*) FROM students ')
count=cursor.fetchone()[0]
print(f"Dataframe 'college.db' created successfully")
print(f"Table 'students' has {count} rows")

cursor.execute("PRAGMA table_info(students)")
columns_info = cursor.fetchall()
print("Table structure of 'students':")
print(f"{'Column Name' :<25} {'Data Type' :<12}")
print("-" * 38)
for col in columns_info:
  print(f"{col[1]:<25} {col[2]:<12}")

def run_query(sql, description=""):
  if description:
    print(f"\n{'='*55}")
    print(f"{description}")
    print(f"{'='*55}")
    result = pd.read_sql_query(sql, conn)
    print(result)
    return result

query1 = """
    SELECT student_id, name, department, math_score, attendance_percentage
    FROM students
    LIMIT 10
"""
result1 = run_query(query1, "Query 1: First 10 Students(SELECT + LIMIT)")
print(result1)

query1 = """
    SELECT student_id, name, department, math_score, attendance_percentage
    FROM students
    LIMIT 5 OFFSET (SELECT COUNT(*) FROM students) - 5
"""
result1 = run_query(query1, "Query 1: Last 5 Students (OFFSET only)")

query2 = """
   SELECT name, department, math_score
   FROM students
   ORDER BY math_score DESC
   LIMIT 5
"""
result2 = run_query(query2, "Query 2: Top 5 Students by Math Score")
print(result2)

query2 = """
    SELECT student_id, name, department, math_score, attendance_percentage, programming_score
    FROM students
    WHERE programming_score >= 50 AND programming_score < 75
"""
result2 = run_query(query2, "Query 2: Students with programming_score between 50 and 75")

query3 = """
     SELECT name,math_score,science_score,programming_score,attendance_percentage
     FROM students
     WHERE department = 'Computer Science'
     ORDER BY programming_score DESC
"""
result3 = run_query(query3, "Query 3: Students in Computer Science Department")

unique_departments_query = """
    SELECT DISTINCT department FROM students
"""
unique_departments = run_query(unique_departments_query, "Fetching Unique Departments")['department'].tolist()

for department in unique_departments:
    query_top_students = f"""
        SELECT
            student_id,
            name,
            department,
            math_score,
            science_score,
            english_score,
            programming_score,
            attendance_percentage
        FROM
            students
        WHERE
            department = '{department}'
        ORDER BY
            programming_score DESC
        LIMIT 5
    """
    run_query(query_top_students, f"Top 5 Students in {department} Department by Programming Score")

print(f"\n{'='*55}")
print(f"Overall Top 5 Students by Programming Score")
print(f"{'='*55}")
overall_top_5_programming = df.nlargest(5, 'programming_score')
display(overall_top_5_programming[['name', 'department', 'programming_score', 'math_score', 'science_score', 'english_score']])

query4 = """
    SELECT name, department, attendance_percentage
    FROM students
    WHERE attendance_percentage > 90
    AND department != 'Civil'
    ORDER BY attendance_percentage DESC
"""
result4 = run_query(query4, "Query 4: Students with High Attendance")

conn = sqlite3.connect('college.db')
dept_data = {
    'dept_code': ['CS', 'EC', 'CE','ME'],
    'dept_name': ['Computer Science', 'Electrical', 'Civil', 'Mechanical'],
    'hod_name': ['Dr.Sharma', 'Dr.Reddy', 'Dr.Patel', 'Dr.Kumar'],
    'established': [1985,1988,1972,1965],
    'intake': [60,60,60,60]
}
dept_df = pd.DataFrame(dept_data)
dept_df.to_sql('departments', conn, if_exists='replace', index=False)
print("Created 'departments' table:")
print(dept_df.to_string(index=False))
dept_map = {
    'Computer Science': 'CS',
    'Electrical': 'EC',
    'Civil': 'CE',
    'Mechanical': 'ME'
}
dept_df['dept_code'] = dept_df['dept_name'].map(dept_map)
dept_df
dept_df.to_sql('departments', conn, if_exists='replace', index=False)
print("Updated 'departments' table:")
print(dept_df.to_string(index=False))
conn.commit()
conn.close()

query_join = """
      SELECT
         s.name,
         s.math_score,
         d.dept_name,
         d.hod_name,
         d.established
      FROM students AS s
      INNER JOIN departments AS d
      ON s.dept_id = d.dept_id
      ORDER BY s.math_score DESC
      LIMIT 8
"""

conn = sqlite3.connect('college.db')
query_full_outer_join = """
    SELECT
        s.name AS student_name,
        s.department AS student_department,
        d.hod_name AS department_hod
    FROM
        students AS s
    LEFT JOIN
        departments AS d ON s.department = d.dept_name
    UNION
    SELECT
        s.name AS student_name,
        s.department AS student_department,
        d.hod_name AS department_hod
    FROM
        departments AS d
    LEFT JOIN
        students AS s ON d.dept_name = s.department
    WHERE s.department IS NULL
"""
result_full_outer_join = run_query(query_full_outer_join, "Simulated FULL OUTER JOIN: All Students and Departments")
conn.close()

conn = sqlite3.connect('college.db')
query_avg_math_by_department = """
SELECT department, AVG(math_score) AS avg_math_score
FROM students
GROUP BY department;
"""
run_query(query_avg_math_by_department, "Average Math Score by Department")
conn.close()

conn = sqlite3.connect('college.db')
query_student_count_by_department = """
SELECT department, COUNT(*) AS student_count
FROM students
GROUP BY department;
"""
run_query(query_student_count_by_department, "Student Count by Department")
conn.close()

conn = sqlite3.connect('college.db')
query_top_8_students_total_score = """
SELECT
    student_id,
    name,
    department,
    (math_score + science_score + english_score + programming_score) AS total_score
FROM students
ORDER BY total_score DESC
LIMIT 8;
"""
run_query(query_top_8_students_total_score, "Top 8 Students by Total Score")
conn.close()

conn = sqlite3.connect('college.db')
query_gender_avg_attendance = """
SELECT gender, AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY gender;
"""
run_query(query_gender_avg_attendance, "Gender-wise Average Attendance")
conn.close()

import pandas as pd
import sqlite3
import matplotlib.pyplot as plt

# Connect database
conn = sqlite3.connect("college.db") # Changed from "students.db" to "college.db"

# Panel 1: Average Programming Score by Department
q1 = """
SELECT department, AVG(programming_score) AS avg_programming
FROM students
GROUP BY department
"""
df1 = pd.read_sql_query(q1, conn)

# Panel 2
q2 = """
SELECT department, COUNT(*) AS student_count
FROM students
GROUP BY department
"""
df2 = pd.read_sql_query(q2, conn)

# Panel 3
q3 = """
SELECT name,
(math_score + science_score + english_score + programming_score) AS total_score
FROM students
ORDER BY total_score DESC
LIMIT 8
"""
df3 = pd.read_sql_query(q3, conn)

# Panel 4
q4 = """
SELECT gender, AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY gender
"""
df4 = pd.read_sql_query(q4, conn)

# Create 2x2 panels
fig, axs = plt.subplots(2, 2, figsize=(12, 8))

# ── Panel 1 (top-left): Avg Programming by Department - BAR Chart ──
axs[0,0].bar(df1['department'], df1['avg_programming'])
axs[0,0].set_title("Average Programming Score by Department")
axs[0,0].set_ylabel("Average Programming Score")

# ── Panel 2 (top-right): Student Count Pie Chart ──
axs[0,1].pie(df2['student_count'],
             labels=df2['department'],
             autopct='%1.1f%%')
axs[0,1].set_title("Student Count by Department")

# ── Panel 3 (bottom-left): Top 8 Students Horizontal Bar ──
axs[1,0].barh(df3['name'], df3['total_score'])
axs[1,0].set_title("Top 8 Students by Total Score")

# ── Panel 4 (bottom-right): Gender Avg Attendance Bar ──
axs[1,1].bar(df4['gender'], df4['avg_attendance'])
axs[1,1].set_title("Average Attendance by Gender")

plt.tight_layout()
plt.show()

conn.close()

conn = sqlite3.connect('college.db')
query_avg_female_programming = """
SELECT AVG(programming_score) AS avg_programming_score
FROM students
WHERE gender = 'Female';
"""
run_query(query_avg_female_programming, "Average Programming Score for Female Students")
conn.close()

#Difference Between WHERE and HAVING
| WHERE                        | HAVING                        |
| ---------------------------- | ----------------------------- |
| Filters rows before grouping | Filters groups after grouping |
| Used with individual rows    | Used with aggregate functions |

conn = sqlite3.connect('college.db')
query_high_attendance_departments = """
SELECT department, AVG(attendance_percentage) AS avg_attendance
FROM students
GROUP BY department
HAVING AVG(attendance_percentage) > 85;
"""
run_query(query_high_attendance_departments, "Departments with Average Attendance Above 85%")
conn.close()

import sqlite3
import pandas as pd

conn = sqlite3.connect('college.db')

query = """
SELECT student_id, name, department, math_score, attendance_percentage
FROM students
LIMIT 5;
"""

df_sample = pd.read_sql_query(query, conn)
print("Sample DataFrame returned by pd.read_sql_query():")
display(df_sample)

conn.close()