# -*- coding: utf-8 -*-
"""DAY9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KBhd4AQRPuOfpZZ91Sk_sMPqq-vp9IL
"""

!pip install groq -q

import sqlite3
import pandas as pd
import os
from groq import Groq
import re
print("All libraries imported sucessfully")

import os
os.environ["GROQ_API_KEY"]="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"
client=Groq(api_key=os.environ["GROQ_API_KEY"])
MODEL="llma-3.1-Bb-instant"
print("Groq client installed sucessfully")
print(f"using model {MODEL}")

import io
csv_data = """student_id,name,age,gender,subject,marks,attendance,grade
1,Aarav Sharma,20,Male,Mathematics,88,92,A
2,Priya Patel,21,Female,Science,76,85,B
3,Rohan Mehta,20,Male,Programming,95,98,A+
4,Sneha Iyer,22,Female,Mathematics,62,78,C
5,Arjun Nair,21,Male,Programming,91,94,A+
6,Divya Krishnan,20,Female,Science,83,88,A
7,Karan Singh,22,Male,Mathematics,74,81,B
8,Ananya Gupta,21,Female,Programming,89,96,A
9,Vikram Reddy,20,Male,Science,70,79,B
10,Pooja Sharma,22,Female,Mathematics,55,72,D
11,Aditya Kumar,21,Male,Programming,97,99,A+
12,Meera Nambiar,20,Female,Science,81,87,A
13,Rahul Desai,22,Male,Mathematics,68,80,C
14,Kavitha Rajan,21,Female,Programming,86,93,A
15,Nikhil Verma,20,Male,Science,77,84,B
16,Swathi Pillai,22,Female,Mathematics,90,95,A+
17,Manish Joshi,21,Male,Programming,73,82,B
18,Lavanya Menon,20,Female,Science,66,76,C
19,Suresh Babu,22,Male,Mathematics,82,89,A
20,Anjali Singh,21,Female,Programming,94,97,A+
21,Deepak Nair,20,Male,Science,79,86,B
22,Rekha Sharma,22,Female,Mathematics,58,73,D
23,Sanjay Patel,21,Male,Programming,88,91,A
24,Usha Iyer,20,Female,Science,84,90,A
25,Vijay Kumar,22,Male,Mathematics,71,83,B
26,Nandita Rao,21,Female,Programming,92,96,A+
27,Ashok Reddy,20,Male,Science,65,77,C
28,Sunita Gupta,22,Female,Mathematics,87,93,A
29,Ravi Krishnan,21,Male,Programming,78,88,B
30,Bhavna Mehta,20,Female,Science,93,98,A+"""
df=pd.read_csv(io.StringIO(csv_data))
print(f"Dataset loaded : {df.shape}")
print("\nFirst 5 rows:")
df.head()

conn = sqlite3.connect("college.db")
df.to_sql("students",conn,if_exists="replace",index=False)
print("Datasets created: college.db")
print("Table 'students'created with 30 students records")
test_df = pd.read_sql_query("SELECT COUNT(*) as total_rows FROM students", conn)
print(f"\nVerification: {test_df['total_rows'][0]}rows in databaes")

def get_schema(conn, table_name='students'):
  cursor = conn.cursor()
  cursor.execute(f"PRAGMA table_info({table_name})")
  columns = cursor.fetchall()

  schema_lines = [f"Table: {table_name}"]
  schema_lines.append("Columns:")

  for col in columns:
    schema_lines.append(f"  - {col[1]} ({col[2]})")
  cursor.execute(f"SELECT * FROM {table_name} LIMIT 3")
  sample_rows = cursor.fetchall()
  schema_lines.append("\nSample rows (first 3):")

  for row in sample_rows:
    schema_lines.append(f"   {row}")
  return "\n".join(schema_lines)

schema = get_schema(conn)
print(schema)

def generate_sql(user_question, schema_text, client, model):
  system_prompt = f"""You are an expert SQL assistant.
  You are connected to a SQLite database with the following structure:

  {schema_text}

  Rules you must follow:
  1. Generate ONLY a valid SQLite SQL query.
  2. Do not include any explanation or text — only the SQL query.
  3. Do not use markdown code blocks. Return the raw SQL only.
  4. The table name is: students
  5. Only use column names that exist in the schema above.
  6. Use single quotes for string values in WHERE clauses (example: WHERE subject = 'Programming').
  7. If the user asks for top N, use ORDER BY marks DESC LIMIT N.
  """

  response = client.chat.completions.create(
      model=model,
      messages=[
          {"role": "system", "content": system_prompt},
          {"role": "user", "content": user_question}
      ],
      temperature = 0.0
  )
  sql_query = response.choices[0].message.content.strip()
  return sql_query

question = "Show me all female students"
print(f"Question: {question}")
print("\nGenerating SQL...")

# Correcting the model name as the original 'llma-3.1-Bb-instant' was not found
MODEL = "llama-3.1-8b-instant"

sql = generate_sql(question, schema, client, MODEL)
print(f"\nGenerated SQL:\n{sql}")

def execute_sql(sql_query, conn):
  clean_sql = sql_query.strip()
  clean_sql = re.sub(r'```sql\s*','',clean_sql)
  clean_sql = re.sub(r'```\s*','',clean_sql)
  clean_sql = clean_sql.strip()
  try:
    result_df = pd.read_sql_query(clean_sql,conn)
    return result_df,None
  except Exception as e:
    return None,str(e)
print(f"Executing SQL: {sql}")
result, error = execute_sql(sql, conn)
if error:
  print(f"Error : {error}")
else:
  print(f"\nQuery returned{len(result)} rows:")
  print(result)

