# -*- coding: utf-8 -*-
"""DAY7embd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkRKxWNuSvr-mcAKpLZvUUBee6QywYA0
"""

# Uninstall chromadb and all opentelemetry related packages to ensure a clean slate
!pip uninstall -y -q chromadb opentelemetry-api opentelemetry-sdk opentelemetry-proto opentelemetry-exporter-otlp-proto-common opentelemetry-exporter-otlp-proto-grpc opentelemetry-exporter-otlp-proto-http

# Install a specific, stable version of chromadb and let it manage its own opentelemetry dependencies
# Upgrading chromadb to 0.5.0 or newer resolves the numpy 2.0 compatibility issue.
!pip install -q "chromadb>=0.5.0"

# Reinstall sentence-transformers
!pip install -q sentence-transformers
print("Done")

import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer
import chromadb
print("all lib imported")

documents=["ETL is used to clean and tranform data",
           "A vehicle is a mode of transportation",
           "Cars and trucks are popular automibiles",
           "Sql is used to query databases",
           "machine learning trains model on data",
           ]
query_keyboard="vehicle"
print(f"KEYBOARD SEARCH FOR: {query_keyboard}")
print("="*60)
for i, doc in enumerate(documents):
  if query_keyboard.lower() in doc.lower():
    print(f"Document {i+1}: {doc}")

print("Loading embedding model...")
model = SentenceTransformer("all-MiniLM-L6-v2")
print("Model loaded successfully")
print(f"Model products vectors of size: {model.get_sentence_embedding_dimension()}")

sentence = "ETL is used to clean and transform data"
embedding = model.encode(sentence)
print(f"Input Sentence: '{sentence}'")
print()
print(f"Embedding Type: {type(embedding)}")
print(f"Embedding Shape: {embedding.shape}")
print(f"First 10 Numbers: {embedding[:10].round(4)}")
print(f"Min Value: {embedding.min():.4f}")
print(f"Max Value: {embedding.max():.4f}")

sentence=["ETL is used to clean and transform data ",
"Data transformation is the key pipeleine step",
"The sky is blue and the clouds are white",
]
embeddings=model.encode(sentence)
print(f"the number of sentences:{len(sentence)}")
print(f"the shape of the embeddings: {embeddings.shape}")
print()
print()
print("each row is one sentence embedding:")

def cosine_similarity(vec_a,vec_b):
  dot_product=np.dot(vec_a,vec_b)
  norm_a=np.linalg.norm(vec_a)
  norm_b=np.linalg.norm(vec_b)
  return dot_product/(norm_a*norm_b)
sin_01=cosine_similarity(embeddings[0],embeddings[1])
sin_02=cosine_similarity(embeddings[0],embeddings[2])
sin_12=cosine_similarity(embeddings[1],embeddings[2])
print("cosine similarity scores")
print("="*60)
print(f"sentence 0 and sentence 1: {sin_01:.4f}")
print(f"sentence 0 and sentence 2: {sin_02:.4f}")
print(f"sentence 1 and sentence 2: {sin_12:.4f}")
print()
print(f"similarity(0 vs 1):{sin_01:.4f}")
print(f"similarity(0 vs 2):{sin_02:.4f}")
print(f"similarity(1 vs 2):{sin_12:.4f}")
print()
print("Insight:sentence 0 and 1 have different words but similae meaning")
print("their cosine similarity score is hifh -the embedding captured the meaning")

