# -*- coding: utf-8 -*-
"""Phase1_Capstone_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BDhFwjZIyIdqB9903yS8Tc-KSR6rqSF
"""

print("===================================")
print("STEP 1 : DATASET SELECTION")
print("===================================")

print("Dataset Name : Global Food Wastage Dataset (2018-2024)")
print("Dataset File : food_waste.csv")
print("Status : Dataset Downloaded Successfully")

print("===================================")
print("STEP 2 : IMPORT LIBRARIES")
print("===================================")

import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries Imported Successfully")

print("===================================")
print("STEP 3 : LOAD DATASET")
print("===================================")

df = pd.read_csv("global_food_wastage_dataset.csv")

print("Dataset Loaded Successfully")

print("===================================")
print("DATASET OVERVIEW")
print("===================================")

print(df.head())

print("===================================")
print("DATASET SHAPE")
print("===================================")

print(df.shape)

print("===================================")
print("COLUMN NAMES")
print("===================================")

print(df.columns.tolist())

df.dtypes

df.isnull().sum()

print("===================================")
print("DUPLICATE RECORDS")
print("===================================")

print("Duplicate Rows :", df.duplicated().sum())

print("===================================")
print("REMOVE DUPLICATES")
print("===================================")

before = len(df)

df = df.drop_duplicates()

after = len(df)

print("Rows Before :", before)
print("Rows After :", after)
print("Duplicates Removed :", before-after)

print("===================================")
print("HANDLE MISSING VALUES")
print("===================================")

num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna("Unknown")

print("Missing Values Handled Successfully")

print("===================================")
print("RENAME COLUMNS")
print("===================================")

df.columns = df.columns.str.replace(" ","_")

print(df.columns.tolist())

print("===================================")
print("SAVE CLEANED DATASET")
print("===================================")

df.to_csv(
    "cleaned_food_waste.csv",
    index=False
)

print("cleaned_food_waste.csv Saved Successfully")

print("===================================")
print("SQLITE DATABASE CREATION")
print("===================================")

conn = sqlite3.connect("food_waste.db")

print("Database Created Successfully")

print("===================================")
print("LOAD DATA INTO DATABASE")
print("===================================")

df.to_sql(
    "food_waste",
    conn,
    if_exists="replace",
    index=False
)

print("Data Loaded Successfully")

print("===================================")
print("VERIFY RECORD COUNT")
print("===================================")

query = """
SELECT COUNT(*)
FROM food_waste
"""

result = pd.read_sql(query,conn)

print(result)

print("===================================")
print("SQL QUERY 1 : FILTERING")
print("===================================")

query = """
SELECT *
FROM food_waste
WHERE Country='India'
"""

result = pd.read_sql(query,conn)

print(result.head())

query = """
PRAGMA table_info(food_waste);
"""

print(pd.read_sql(query, conn))

print("===================================")
print("SQL QUERY 2 : SORTING")
print("===================================")

query = """
SELECT *
FROM food_waste
ORDER BY "Economic_Loss_(Million_$)" DESC
"""

result = pd.read_sql(query,conn)

print(result.head())

print("===================================")
print("SQL QUERY 3 : AGGREGATION")
print("===================================")

query = """
SELECT SUM("Total_Waste_(Tons)")
AS Total_Waste
FROM food_waste
"""

result = pd.read_sql(query,conn)

print(result)

print("===================================")
print("SQL QUERY 4 : GROUP BY")
print("===================================")

query = """
SELECT Country,
SUM("Total_Waste_(Tons)")
AS Waste
FROM food_waste
GROUP BY Country
"""

result = pd.read_sql(query,conn)

print(result.head())

print("===================================")
print("SQL QUERY 5 : CONDITIONAL QUERY")
print("===================================")

query = """
SELECT *,
CASE
WHEN "Total_Waste_(Tons)" > 1000
THEN 'High'
ELSE 'Low'
END AS Waste_Level
FROM food_waste
"""

result = pd.read_sql(query,conn)

print(result.head())

print("===================================")
print("SQL TRANSFORMATION")
print("===================================")

query = """
SELECT *,

CASE
    WHEN "Total_Waste_(Tons)" > 7000 THEN 'High'
    WHEN "Total_Waste_(Tons)" > 4000 THEN 'Medium'
    ELSE 'Low'
END AS Waste_Category,

CASE
    WHEN "Economic_Loss_(Million_$)" > 500
    THEN 'Critical Loss'
    ELSE 'Normal Loss'
END AS Loss_Status

FROM food_waste
"""

transformed_df = pd.read_sql(query, conn)

print(transformed_df.head())

transformed_df.to_csv(
    "transformed_food_waste.csv",
    index=False
)

print("Transformed Dataset Saved Successfully")

plt.figure(figsize=(10,5))

top10 = df.groupby("Country")["Total_Waste_(Tons)"]\
          .sum()\
          .sort_values(ascending=False)\
          .head(10)

top10.plot(kind="bar")

plt.title("Top 10 Countries by Food Waste")
plt.ylabel("Waste (Tons)")
plt.show()

plt.figure(figsize=(8,8))

df["Food_Category"]\
.value_counts()\
.plot(kind="pie", autopct="%1.1f%%")

plt.ylabel("")
plt.title("Food Category Distribution")

plt.show()

plt.figure(figsize=(10,5))

sns.lineplot(
    data=df,
    x="Year",
    y="Economic_Loss_(Million_$)"
)

plt.title("Economic Loss Trend")
plt.show()

print("===================================")
print("MACHINE LEARNING MODEL")
print("===================================")

from sklearn.preprocessing import LabelEncoder

le_country = LabelEncoder()
le_food = LabelEncoder()

df["Country"] = le_country.fit_transform(df["Country"])
df["Food_Category"] = le_food.fit_transform(df["Food_Category"])

X = df[
[
'Country',
'Year',
'Food_Category',
'Total_Waste_(Tons)',
'Avg_Waste_per_Capita_(Kg)',
'Population_(Million)',
'Household_Waste_(%)'
]
]

y = df['Economic_Loss_(Million_$)']

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Records :", len(X_train))
print("Testing Records :", len(X_test))

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train,y_train)

print("Model Trained Successfully")

pred = model.predict(X_test)

print("Prediction Completed")

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

print("MAE :", mean_absolute_error(y_test,pred))
print("R2 Score :", r2_score(y_test,pred))

