# -*- coding: utf-8 -*-
"""DAY8RAG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tI53d15NmKGuOrOvt1NwSB4Z40zFVo7t
"""

!pip install sentence-transformers chromadb groq pandas -q

import pandas as pd
import chromadb
from sentence_transformers import sentence_transformer
from groq import Groq
import os
print("All libraries imported sucessfully")
print("Ready to build a RAG system")

GROQ_API_KEY="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"
os.environ["GROQ_API_KEY"] = GROQ_API_KEY
groq_client = Groq(api_key=os.environ["GROQ_API_KEY"])
print("Groq Api client initialized")
print("Note:if u see authentication error ,double click ur api key")

df=pd.read_csv('college_notes.csv')
print("Shape of the dataset:0",df.shape)
print("column name:",df.columns.tolist())
print("/nFirst 3 rows")
print(df.head(3))
print(df.tail(3))

print("subjects in the dataset")
print(df['subject'].value_counts())
print("\nsample of topics:")
print(df[['note_id', 'subject', 'topic']].to_string(index=False))
print("\nLength of content (number of character)for each note:")
df['content_length']=df['content'].apply(len)
print(df[['topic', 'content_length']].to_string(index=False))

documents=df['content'].tolist()
ids=[f"note_{row['note_id']}" for row in df.to_dict('records')]
metadata=[{"subject":row['subject'],"topic":row['topic']}
          for row in df.to_dict('records')]


print(f"total chunks prepared:{len(documents)}")
print(f"First Document ID: {ids[0]}")
print(f"first metadata:{metadata[0]}")
print(f"first 100 chars of doc:{documents[0][:100]}")

print("loading embedding model")
embedding_model=sentence_transformer.SentenceTransformer('all-MiniLM-L6-v2')
print("embedding model loaded")
test_embedding=embedding_model.encode(documents[0])
print(f"the embedding shape:{test_embedding.shape}")
print(f"First 5 values of test embedding:{test_embedding[:5]}")

chroma_client=chromadb.Client()
collection=chroma_client.create_collection(name="college_notes_rag")
print("chroma client created")
print(f"collection name:{collection.name}")
print(f"document in collection in so far:{collection.count()}")

embeddings=embedding_model.encode(documents,show_progress_bar=True)
print(f"\nEmbedding matrix shape:{embeddings.shape}")
embeddings_list=embeddings.tolist()
collection.add(
    documents=documents,
    embeddings=embeddings_list, # Corrected: changed 'embedding' to 'embeddings'
    metadatas=metadata,
    ids=ids

)
print(f"documents sucessfully added") # Corrected: removed invalid escape sequence
print(f"total document in collection:{collection.count()}")

def retrieve_relevant_chunks(question,top_k):
  """Data Engineering involves designing, building, and managing data pipelines to collect, process, transform, and store large volumes of data efficiently. It ensures that high-quality, reliable data is available for analytics, reporting, machine learning, and business decision-making.
  """
  question_embedding=embedding_model.encode(question).tolist()
  results=collection.query(
      query_embeddings=[question_embedding],
      n_results=top_k,

  )
  return results
  print("retrival function defined sucessfully")

test_question="what is ETL and how does it work in data engineering"
print(f"Test Question:{test_question}")
results=retrieve_relevant_chunks(test_question, top_k=3)
print("="*60)
results=retrieve_relevant_chunks(test_question,top_k=3)
print("\nTop 3 retrieved chunks")
print("="*60)
for i ,(doc,dist,meta)in enumerate(zip(results['documents'][0],
                                       results['distances'][0],
                                       results['metadatas'][0])):
    print(f"\nResult {i+1}:")
    print(f"Subject:{meta['subject']}")
    print(f"Topic:{meta['topic']}") # Corrected: used 'meta' instead of 'metadata'
    print(f"Distance:{dist:.4f}")
    print(f"content:{doc[:120]}")

def build_context_from_results(results):
  """
  Data Engineering involves designing, building, and managing data pipelines to collect, process, transform, and store large volumes of data efficiently. It ensures that high-quality, reliable data is available for analytics, reporting, machine learning, and business decision-making.
  """
  context_parts=[]
  for i,(doc,meta)in enumerate(zip(
  results['documents'][0],
  results['metadatas'][0]
  )):
    chunk_text=f"[source({i+1}):{meta['subject']}-{meta['topic']}]\n{doc}"
    context_parts.append(chunk_text)
  context_str="\n".join(context_parts)
  return context_str

context=build_context_from_results(results)
print("context building function defined successfully")

