# -*- coding: utf-8 -*-
"""FAISS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ppPn0WXxMHJMwYwE3XSCN1Ls2mYoUaBZ
"""

!pip install langchain langchain-community langchain-groq faiss-cpu sentence-transformers PyPDF2 pypdf --q

!pip install fpdf --q

from fpdf import FPDF
import os
pdf=FPDF()
pdf.add_page()
pdf.set_font("Arial",size=12)
content=[
    "Developed end-to-end ETL pipelines using Python, Pandas, and SQL.",
    "Performed data cleaning, transformation, and preprocessing on large datasets.",
    "cat can spend 16-20 hours a day sleeping"
]
for line in content:
  pdf.multi_cell(0,10,line)
pdf_file="ragg.pdf"
pdf.output(pdf_file)
print(f"PDF saved as {pdf_file}")
os.listdir(".")

import os
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq
os.environ["GROQ_API_KEY"] = "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"
loader = PyPDFLoader("ragg.pdf")
pages = loader.load()
splitter = CharacterTextSplitter(chunk_size=500,chunk_overlap=50)
documents = splitter.split_documents(pages)
embedding = HuggingFaceEmbeddings(
model_name="sentence-transformers/all-MiniLM-L6-v2")
db = FAISS.from_documents(documents, embedding)
llm = ChatGroq(model_name="llama-3.1-8b-instant")
prompt = PromptTemplate.from_template("""
Use the following context to answer the question.
Context:{context},Question:{question},Answer:
"""
)
parser = StrOutputParser()
def ask_pdf(query: str):
    docs = db.similarity_search_with_score(query, k=3)
    context = "\n\n".join([d[0].page_content for d in docs])
    chain = prompt | llm | parser
    return chain.invoke({"context": context,"question": query})
while True:
    query = input("\nAsk a question (or type 'exit'): ")
    if query.lower() == "exit":
        break
    answer = ask_pdf(query)
    print("\nAnswer:\n", answer)

from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser
import os
os.environ["GROQ_API_KEY"] = "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"
llm = ChatGroq(model_name="llama-3.1-8b-instant")
prompt = PromptTemplate.from_template("""
You are an expert Python programmer.
Generate only the code for the following requirement:
{question}
Code:
"""
)
parser = StrOutputParser()
chain = prompt | llm | parser
query = input("Enter your requirement: ")
response = chain.invoke({"question": query})
print("\nGenerated Code:\n")
print(response)

