# -*- coding: utf-8 -*-
"""DAY5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bAuP4o-qK_fCLigj3XYhs1NK795gv1ko
"""

import pandas as pd
import numpy as np
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error,r2_score
print("All libraries imported successfully!")

df = pd.read_csv('/content/student_performance.csv')
display(df.head())

df_ml=df.copy()

le_gender=LabelEncoder()
df_ml['gender_encoded']=le_gender.fit_transform(df_ml['gender'])
print(f'gender encoding: {dict(zip(le_gender.classes_,le_gender.transform(le_gender.classes_)))}')

le_dept=LabelEncoder() # Corrected LabelEncoder capitalization
df_ml['department_encoded']=le_dept.fit_transform(df_ml['department']) # Corrected column name to 'department'
print(f'department encoding: {dict(zip(le_dept.classes_,le_dept.transform(le_dept.classes_)))}')

print('\nNew columns added: gender_encoded, department_encoded')
df_ml[['gender','gender_encoded','department','department_encoded']].head(5) # Corrected column names for display

# ============================================================
# CELL 5 — Select features and define target
# ============================================================

# FEATURES (X): the input columns the model will learn from
feature_cols = [
    'math_score',
    'science_score',
    'english_score',
    'attendance_percentage',
    'gender_encoded',
    'department_encoded'
]


X = df_ml[feature_cols]


y = df_ml['programming_score']


print(f'Feature matrix X shape: {X.shape}  (students × features)')
print(f'Target vector y shape : {y.shape}  (one score per student)')
print(f'\nFeature columns: {feature_cols}')
print(f'Target column  : programming_score')
print(f'\nTarget range: {y.min()} to {y.max()} (mean: {y.mean():.1f})')



