# -*- coding: utf-8 -*-
"""Langchain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6EZhvnV03qh3HQ_c2lt7Sb-EGnST_v-
"""

!pip install langchain langchain-groq langchain-community langchain-core --quiet

import os
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

os.environ["GROQ_API_KEY"]="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"
llm=ChatGroq(model="llama-3.3-70b-versatile",temperature=0)
prompt=PromptTemplate(
    input_variables=["instruction"],
    template="You are an expert Python programmer Explain concepts in simple language with examples :\n\nInstruction:{instruction}\n\nAnswer:"
)
parser=StrOutputParser()
chain=prompt|llm|parser
response=chain.invoke({
    "instruction": "Explain list comprehension in Python"
})
print("\nnZeroshot-Output:\n",response)

