# -*- coding: utf-8 -*-
"""Day4(twilio).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XbL6x-N92YD9Pte35N0LADENS2XcFSHp
"""

!pip install twilio --quiet

import os
from twilio.rest import Client
from getpass import getpass
# --- Twilio credentials ---
TW_SID = os.environ.get('TWILIO_SID')
TW_TOKEN = os.environ.get('TWILIO_TOKEN')

if not TW_SID or not TW_TOKEN:
    print("Enter your Twilio Account SID and Auth Token:")
    TW_SID = getpass("Twilio SID: ")
    TW_TOKEN = getpass("Twilio Token: ")
    os.environ['TWILIO_SID'] = TW_SID
    os.environ['TWILIO_TOKEN'] = TW_TOKEN