# -*- coding: utf-8 -*-
"""Day_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHoF465-QBuvjIQ3IZgwIboJZlUYZTPM
"""

import requests
import pandas as pd

# API URL
url = "https://api.open-meteo.com/v1/forecast?latitude=13.08&longitude=80.27&current_weather=true"

# Extract
response = requests.get(url)
data = response.json()

# Transform
weather_data = {
    "Temperature": [data['current_weather']['temperature']],
    "Wind Speed": [data['current_weather']['windspeed']],
    "Weather Code": [data['current_weather']['weathercode']]
}

df = pd.DataFrame(weather_data)

# Load
df.to_csv("weather_data.csv", index=False)

print(df)

import pandas as pd

print("=" * 50)
print("EMPLOYEE SALARY ETL PROJECT")
print("=" * 50)

# -----------------------------
# EXTRACT
# -----------------------------

# Load dataset
df = pd.read_csv("employee_salary.csv")

print("\nOriginal Dataset:")
print(df)

# Dataset overview
print("\nTotal Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

# -----------------------------
# TRANSFORM
# -----------------------------

# Remove duplicate rows
duplicate_count = df.duplicated().sum()
print(f"\nDuplicate Rows Found: {duplicate_count}")

df = df.drop_duplicates()

# Fill missing salary values
median_salary = df['monthly_salary'].median()

df['monthly_salary'] = df['monthly_salary'].fillna(median_salary)

print(f"Filled missing salary with median value: {median_salary}")

# Standardize employee names
df['employee_name'] = df['employee_name'].str.strip().str.title()

# Calculate yearly salary
df['yearly_salary'] = df['monthly_salary'] * 12

print("\nCleaned Dataset:")
print(df)

# -----------------------------
# LOAD
# -----------------------------

# Export cleaned dataset
df.to_csv("cleaned_employee_salary.csv", index=False)

print("\nCleaned dataset exported successfully!")

# -----------------------------
# ANALYSIS
# -----------------------------

print("\nAverage Monthly Salary:")
print(df['monthly_salary'].mean())

print("\nHighest Salary:")
print(df['monthly_salary'].max())

print("\nLowest Salary:")
print(df['monthly_salary'].min())